[workspace]
members = [ 
    "inspector", 
    "config",
    "hoopics", 
    "ollama",
    "psql", 
    "service", 
    "worker", 
    "sdxl", 
    "primitives", 
    "dispatcher", 
    "refresher"
, "flux", "censorship"]
resolver = "2"

