[hoopics]
api_key = "your_api_key_here"
endpoint = "https://api.hoopics.com/v1/"

[ollama]
model = "impactframes/llama3_ifai_sd_prompt_mkr_q4km"
url = "https://u447140-b619-b81b9121.bjb1.seetacloud.com:8443/ollama/generate"

[postgres]
host = "127.0.0.1"
port = 5432
user = "postgres"
password = "111"
dbname = "hoopd"

[sdxl]
normal = "https://u447140-b619-b81b9121.bjb1.seetacloud.com:8443"

[flux]
normal = "https://u447140-9ec2-9aec6315.bjb1.seetacloud.com:8443"

# 单位秒: txt2img / img2img 都需要时间，定期去SDX、FLUX上查询status
[refresher]
sdxl_interval = 15 # sdxl 速度快
flux_interval = 30 # flux 速度慢