[service]
api_key = "your_api_key_here"
endpoint = "127.0.0.1"
port = 3030

[ollama]
url = "https://u447140-b619-b81b9121.bjb1.seetacloud.com:8443/ollama/generate"
model = "impactframes/llama3_ifai_sd_prompt_mkr_q4km"

[postgres]
host = "127.0.0.1"
port = 5432
user = "postgres"
password = "111"
dbname = "hoopd"

[sdxl]
normal = "https://u447140-b619-b81b9121.bjb1.seetacloud.com:8443"
cartoon = "https://u447140-b619-b81b9121.bjb1.seetacloud.com:8443"
cyberpunk = "https://u447140-b619-b81b9121.bjb1.seetacloud.com:8443"
film = "https://u447140-b619-b81b9121.bjb1.seetacloud.com:8443"

[flux]
normal = "https://u447140-9ec2-9aec6315.bjb1.seetacloud.com:8443"
cartoon = "https://u447140-9ec2-9aec6315.bjb1.seetacloud.com:8443"
cyberpunk = "https://u447140-9ec2-9aec6315.bjb1.seetacloud.com:8443"
film = "https://u447140-9ec2-9aec6315.bjb1.seetacloud.com:8443"

# 单位秒: txt2img / img2img 都需要时间，定期去SDX、FLUX上查询status
[refresher]
print_log = true # 是否打印日志到terminal
sdxl_interval = 15 # sdxl 速度快
flux_interval = 30000000000 # flux 速度慢

[checkpoints]
max_length_prompt = 1500
max_length_negative_prompt = 200
max_length_description = 200
max_length_img_link = 256
max_image_width = 1024
min_image_width = 1
max_image_height = 1024
min_image_height = 1

[worker]
max_buffer_size = 100 # worker 的 channel buffer size 设置
