[package]
name = "psql"
version = "0.1.0"
edition = "2021"

[dependencies]
config = { path = "../config" }
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
postgres = "0.19.9"
primitives = { path = "../primitives" }