[package]
name = "dispatcher"
version = "0.1.0"
edition = "2021"

[dependencies]
primitives = { path = "../primitives" }
sdxl = { path = "../sdxl" }
reqwest = { version = "0.11", features = ["json"] }
psql = { path = "../psql" }
tokio-postgres = { version = "0.7.12" }
flux = { path = "../flux" }
